### PR TITLE
[DO NOT MERGE] Looking at how CI works.

### PR DESCRIPTION
**Pull request by gregtatum**

### CODE REVIEW

**Comment by gregtatum** [comment]
Looks like the CI isn't hooked up?
edit: nevermind, there it goes.

**Comment by gregtatum** [comment]
Now it says "No TaskCluster jobs started for this pull request". Should this be doing something?

**Comment by juliandescottes** [comment]
I'm not sure why the CI didn't kick in here. I tried sending some similar PRs: #20 and #21. 
I wanted to check if sending PRs from forks might be a problem since I had never tried before.

Both got CI jobs attached. Could you try pushing an additional commit here?

**Comment by gregtatum** [comment]
@juliandescottes ok, just pushed another one on.

**Comment by juliandescottes** [comment]
Still nothing :( 

(for the record the history of master gets rewritten everyday to remain in sync with mozilla-central, until we officially switch to github, `reference` is a stable branch you can use)

**Comment by mykmelez** [comment]
> I'm not sure why the CI didn't kick in here. I tried sending some similar PRs: #20 and #21.
> I wanted to check if sending PRs from forks might be a problem since I had never tried before.
> 
> Both got CI jobs attached. Could you try pushing an additional commit here?

@juliandescottes Perhaps you're a collaborator on this repository? Its .taskcluster.yml file doesn't have an *allowPullRequests* property, and per https://docs.taskcluster.net/reference/integrations/taskcluster-github/docs/usage#who-can-trigger-jobs-, the default value of that property is `collaborators`, which is described:

> tasks are created if the user who made the pull request is a collaborator on the repository. Github defines collaborators as "outside collaborators, organization members with access through team memberships, organization members with access through default organization permissions, and organization owners."

If you want a pull request from a non-collaborator to trigger TaskCluster CI, you'll need to set *allowPullRequests* to `public` (f.e. as I did in this other repository: https://github.com/mozilla/qbrt/blob/master/.taskcluster.yml#L2).

**Comment by mykmelez** [comment]
> @juliandescottes ok, just pushed another one on.

@gregtatum Note that you can push an "empty change" to a pull request by committing with the --allow-empty flag:

> git commit --allow-empty

**Comment by juliandescottes** [comment]
Thanks for the feedback @mykmelez , I am a contributor indeed so that's probably it.

**Comment by ochameau** [comment]
Hi Greg, we pushed an update that should allow you to trigger the CI, could you try rebasing your branch?
Thanks @mykmelez, that should be that.

**Pull request closed without merging**
